### ISSUE TITLE
Travis Testing Fails for unknown reason

### ISSUE THREAD

**Issue by glenfletcher** [glenfletcher/Equation#21]
running `python setup.py test` locally works but when its run by travis raises `AttributeError: 'module' object has no attribute 'test_Equation'`

```
E:\Git\Equation>python setup.py test
running test
running egg_info
writing requirements to Equation.egg-info\requires.txt
writing Equation.egg-info\PKG-INFO
writing top-level names to Equation.egg-info\top_level.txt
writing dependency_links to Equation.egg-info\dependency_links.txt
reading manifest file 'Equation.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Equation.egg-info\SOURCES.txt'
running build_ext
testCall (tests.test_Equation.TestAddEquation) ... ok
....

----------------------------------------------------------------------
Ran 66 tests in 0.010s

OK
```

Travis (https://travis-ci.org/alphaomega-technology/Equation/builds/27294215) outputs 

```
Using worker: worker-linux-6-1.bb.travis-ci.org:travis-linux-19

$ export TOX_ENV=py27
travis_fold:start:git.1
$ git clone --depth=50 --branch=rounding git://github.com/alphaomega-technology/Equation.git alphaomega-technology/Equation
Cloning into 'alphaomega-technology/Equation'...
remote: ...
Receiving objects:   ...
Resolving deltas:   ...
Resolving deltas: 100% (153/153), done.
Checking connectivity... done.
travis_fold:end:git.1
$ cd alphaomega-technology/Equation
travis_fold:start:git.3
$ git checkout -qf e621c7c36749d61f4e7af0ef60739a5b0ea5a27c
travis_fold:end:git.3
$ source ~/virtualenv/python2.7/bin/activate
$ python --version
Python 2.7.6
$ pip --version
pip 1.5.4 from /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages (python 2.7)
travis_fold:start:install
$ pip install tox
Downloading/unpacking tox
  Downloading tox-1.7.1.tar.gz (84kB): ...
  Running setup.py (path:/home/travis/virtualenv/python2.7.6/build/tox/setup.py) egg_info for package tox

Downloading/unpacking virtualenv>=1.11.2 (from tox)
  Downloading virtualenv-1.11.6-py2.py3-none-any.whl (1.6MB): ...
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in /home/travis/virtualenv/python2.7.6/lib/python2.7/site-packages (from tox)
Installing collected packages: tox, virtualenv
  Running setup.py install for tox

    Installing tox script to /home/travis/virtualenv/python2.7.6/bin
    Installing tox-quickstart script to /home/travis/virtualenv/python2.7.6/bin
Successfully installed tox virtualenv
Cleaning up...
travis_fold:end:install
$ tox -e $TOX_ENV
sdist-make: /home/travis/build/alphaomega-technology/Equation/setup.py
create: /home/travis/build/alphaomega-technology/Equation/.tox/py27
installdeps: -r/home/travis/build/alphaomega-technology/Equation/requirements.txt
inst: /home/travis/build/alphaomega-technology/Equation/.tox/dist/Equation-1.1.dev-20140611.zip
runtests: PYTHONHASHSEED='553858082'
runtests: commands[0] | python setup.py test
running test
running egg_info
writing dependency_links to Equation.egg-info/dependency_links.txt
writing Equation.egg-info/PKG-INFO
writing top-level names to Equation.egg-info/top_level.txt
writing requirements to Equation.egg-info/requires.txt
reading manifest file 'Equation.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Equation.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 48, in <module>
    test_suite='tests',
  File "/opt/python/2.7.6/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/opt/python/2.7.6/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.7.6/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/travis/build/alphaomega-technology/Equation/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 146, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/travis/build/alphaomega-technology/Equation/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 127, in with_project_on_sys_path
    func()
  File "/home/travis/build/alphaomega-technology/Equation/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 167, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/opt/python/2.7.6/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/opt/python/2.7.6/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/opt/python/2.7.6/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/opt/python/2.7.6/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/python/2.7.6/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/travis/build/alphaomega-technology/Equation/.tox/py27/lib/python2.7/site-packages/setuptools/command/test.py", line 39, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/opt/python/2.7.6/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_Equation'
ERROR: InvocationError: '/home/travis/build/alphaomega-technology/Equation/.tox/py27/bin/python setup.py test'
___________________________________ summary ____________________________________
ERROR:   py27: commands failed

The command "tox -e $TOX_ENV" exited with 1.

Done. Your build exited with 1.
```

Anyone have any ideas as to the cause?

**Comment by bwrsandman** [comment]
Pretty sure this can be closed, you have a more simple travis config
