### ISSUE TITLE
Python 2.6 No importlib

### ISSUE THREAD

**Issue by glenfletcher** [glenfletcher/Equation#24]
```
$ git clone --depth=50 --branch=rounding git://github.com/alphaomega-technology/Equation.git alphaomega-technology/Equation
Cloning into 'alphaomega-technology/Equation'...
$ cd alphaomega-technology/Equation
travis_fold:start:git.3
$ git checkout -qf a0684d8936a46f89a2214fe3c0b6dacd1fd23756
travis_fold:end:git.3
$ source ~/virtualenv/python2.6/bin/activate
$ python --version
Python 2.6.9
$ pip --version
pip 1.5.4 from /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages (python 2.6)
travis_fold:start:install
$ pip install -r requirements.txt
[33mYou must give at least one requirement to install (see "pip help install")
[0mtravis_fold:end:install
$ python setup.py test
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    import Equation as pkg
  File "/home/travis/build/alphaomega-technology/Equation/Equation/__init__.py", line 85, in <module>
    load()
  File "/home/travis/build/alphaomega-technology/Equation/Equation/__init__.py", line 48, in load
    import importlib
ImportError: No module named importlib

[31;1mThe command "python setup.py test" exited with 1.

Done. Your build exited with 1.
```

**Comment by glenfletcher** [comment]
Fixed in Bug-Fix#24
